version: '3'
services: 
  todotests:
    image: todotests
    environment:
      - FRONT_HOST=todofront
    depends_on:
      - todoback
      - todofront
  todofront:
    image: todofrontend
    depends_on:
      - todoback
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_HOST=todoback
  todoback:
    image: todobackend
    ports:
      - 3001:3001

